export const events = [
    {
        id: "1",
        image: "/Images/church_1.png",
        date: "Nov 19, 2024",
        title: "Help End Water Crisis for Families",
        description: "This is a short description of the blog post to give the reader an idea of its content.",
        btn: "Details",
    },
    {
        id: "2",
        image: "/Images/church_2.png",
        date: "Nov 18, 2024",
        title: "Spirit of the lord is from the New life",
        description: "An engaging description for another blog post to entice readers to click.",
        btn: "Details",
    },
    {
        id: "3",
        image: "/Images/church_3.png",
        date: "Nov 17, 2024",
        title: "Innocent But not wise a book by Bro Gbile",
        description: "A third description to demonstrate mapping through an array of blog posts.",
        btn: "Details",
    },
    {
        id: "4",
        image: "/Images/church_1.png",
        date: "Nov 19, 2024",
        title: "Help End Water Crisis for Families",
        description: "This is a short description of the blog post to give the reader an idea of its content.",
        btn: "Details",
    },
    {
        id: "5",
        image: "/Images/church_2.png",
        date: "Nov 18, 2024",
        title: "Spirit of the lord is from the New life",
        description: "An engaging description for another blog post to entice readers to click.",
        btn: "Details",
    },
    {
        id: "6",
        image: "/Images/church_3.png",
        date: "Nov 17, 2024",
        title: "Innocent But not wise a book by Bro Gbile",
        description: "A third description to demonstrate mapping through an array of blog posts.",
        btn: "Details",
    },
];
